/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Dark theme colors (Material Design 3)
        "on-tertiary-fixed-variant": "#6d6d6f",
        "secondary": "#f9e281",
        "on-primary-fixed": "#064a10",
        "surface-dim": "#0e0e0f",
        "secondary-fixed": "#f9e281",
        "error": "#ff7351",
        "on-tertiary-container": "#575658",
        "surface-container-highest": "#262627",
        "tertiary-container": "#edeaec",
        "on-surface-variant": "#adaaab",
        "surface-tint": "#aff4a6",
        "surface-bright": "#2c2c2d",
        "primary": "#aff4a6",
        "on-error-container": "#ffd2c8",
        "on-surface": "#ffffff",
        "primary-container": "#6fb069",
        "inverse-surface": "#fcf8f9",
        "on-secondary-container": "#fff7e5",
        "surface-container-low": "#131314",
        "secondary-fixed-dim": "#ebd474",
        "on-secondary-fixed-variant": "#6b5b00",
        "secondary-container": "#6e5e03",
        "background": "#0e0e0f",
        "on-error": "#450900",
        "surface-container-lowest": "#000000",
        "tertiary-fixed": "#ffffff",
        "primary-fixed": "#aff4a6",
        "on-tertiary-fixed": "#505052",
        "inverse-primary": "#2e6c2d",
        "on-tertiary": "#5f5f61",
        "inverse-on-surface": "#565556",
        "surface-container": "#19191b",
        "on-primary-fixed-variant": "#2a682a",
        "on-background": "#ffffff",
        "on-secondary": "#605100",
        "surface-variant": "#262627",
        "on-secondary-fixed": "#4b3f00",
        "primary-dim": "#a2e599",
        "tertiary-fixed-dim": "#f2f0f2",
        "outline": "#767576",
        "on-primary": "#1f5e21",
        "error-container": "#b92902",
        "surface-container-high": "#1f1f21",
        "primary-fixed-dim": "#a2e599",
        "secondary-dim": "#ebd474",
        "error-dim": "#d53d18",
        "outline-variant": "#484849",
        "surface": "#0e0e0f",
        "tertiary-dim": "#edeaec",
        "tertiary": "#fbf8fb",
        "on-primary-container": "#002a04"
      },
    },
  },
  plugins: [],
};
